### ISSUE TITLE
Functional? 

### ISSUE THREAD

**Issue by antithing** [julienkay/MERF-Unity-Viewer#1]
Hi! Does this code work? Would love to port it to ue5.

Thanks!

**Comment by julienkay** [comment]
As noted in the readme, it's not fully working,. [Only the diffuse part is rendering correctly.](https://twitter.com/julien_kaye/status/1695860680979550312)

For porting to Unreal, [here](https://github.com/google-research/google-research/tree/master/merf/webviewer) is the reference implementation that this is based on.
